In [1]:
import numpy as np

In [4]:
a = np.matrix('1, 2, 3; 4, 5, 6')

In [5]:
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [8]:
b = np.matrix('7, 10; 8, 11; 9, 12')

In [9]:
b

matrix([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [11]:
a*b

matrix([[ 50,  68],
        [122, 167]])

In [12]:
a.dot(b)

matrix([[ 50,  68],
        [122, 167]])

In [13]:
a.sum()

21

In [14]:
a.prod()

720

In [17]:
a.size

6

### Frobenius norm:

$\displaystyle\big|\big|m\big|\big|_{F}=\left( \sum_{i,j=1}^{n} m_{ij}^2\right)^\frac{1}{2} $

In [31]:
np.sqrt(((a*b) ** 2).sum())

297.00336698428185

### Standard Deviation:

$\displaystyle\sqrt{\frac{1}{n-1}\sum_{i=1}^{n}\left(x_{i}-\bar x\right)^2}$

In [35]:
m = np.matrix('2, 3; 4, 7')

In [36]:
np.sqrt((1/(m.size - 1)) * ((m - m.mean()) ** 2).sum())

2.0